### ISSUE TITLE
Pagely domain expired

### ISSUE THREAD

**Issue by nair0lf32** [hilmanski/freeStuffDev#1333]
[pagely.site](http://www.pagely.site/?ref=freeStuffDev) redirects to a page suggesting the domain is on sale. I don't know if
Pagely is now referring to [pagely.com](https://pagely.com/), but this one doesn't seem to offer any free pricing plan and mostly focus on WordPress premium hosting. Pagely should either be removed from the listing if they discontinued their free services or the link should be updated with their new address if there is one.

**Comment by hilmanski** [comment]
thanks for the update. will remove it soon for now
