### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [hilmanski/freeStuffDev#1342]
Hello, I noticed a broken link and run an automated scan for broken links on the repository:

- [ ] https://pbs.twimg.com/profile_images/1412407764169760784/GgzTCE7G_400x400.jpg (file: content/stuff/magic.md, status code: 404)
- [ ] https://pbs.twimg.com/profile_images/1448076077264478210/sOvFsmfL_400x400.jpg (file: content/stuff/mattermost.md, status code: 404)
- [ ] https://metatags.io/assets/favicon-71ffc45e665afe1eb5447e86787278b28f56dfb39a6d53c8603d8477bdee7b6f.png (file: content/stuff/meta-tags.md, status code: 404)
- [ ] https://metamask.io/icons/icon-512x512.png (file: content/stuff/metamask.md, status code: 404)
- [x] https://microletter.cc/ (file: content/stuff/microletter.md, error: EAI_AGAIN)
- [x] https://microletter.cc/assets/img/apple-touch-icon.png?h=c3837d63e810f9dfc826371e22c6c395 (file: content/stuff/microletter.md, error: EAI_AGAIN)
- [x] https://mixpanel.com (file: content/stuff/mixpanel.md, error: ECONNREFUSED)
- [x] https://px6vg4ekvl21gtxs836x5jyx-wpengine.netdna-ssl.com/wp-content/uploads/2020/11/Mixpanel_Favicon_32x32.png (file: content/stuff/mixpanel.md, error: ENOTFOUND)
- [ ] https://pbs.twimg.com/profile_images/1234528105819189248/b6F1hk_6_400x400.jpg (file: content/stuff/mongodb.md, status code: 404)
- [ ] https://pbs.twimg.com/profile_images/1256226546152587264/TQ889kUB_400x400.jpg (file: content/stuff/netdata.md, status code: 404)
- [ ] https://pbs.twimg.com/profile_images/1413544188411482112/61xGHyIi_400x400.jpg (file: content/stuff/netlify.md, status code: 404)
- [ ] https://pbs.twimg.com/profile_images/872125924409528322/YIgPht1s_400x400.jpg (file: content/stuff/netlifycms.md, status code: 404)
- [ ] https://ngrok.com/static/img/favicon.png (file: content/stuff/ngrok.md, status code: 404)
- [ ] https://nhost.io/favicon.png (file: content/stuff/nhost.md, status code: 404)
- [ ] https://nocodeapi.com/icons/icon-512x512.png?v=fc17b99d75c8dfe889cf0f78c646d84b (file: content/stuff/nocodeapi.md, status code: 404)
- [x] https://www.getnotation.com/ (file: content/stuff/notation.md, error: EPROTO)
- [x] https://www.getnotation.com/img/favicon.ico (file: content/stuff/notation.md, error: EPROTO)
- [ ] https://oa.mg/icons/Icon-192.png?ver=1 (file: content/stuff/oamg.md, status code: 404)
- [ ] https://www.octoparse.com/images/logo_blue.png (file: content/stuff/octoparse.md, status code: 404)
- [ ] https://openai.com/assets/images/mask-icon.svg?v=f30375207f (file: content/stuff/openai.md, status code: 404)
- [ ] https://pacomail.io/wp-content/uploads/2022/08/icon-logo-22.svg (file: content/stuff/pacomail.md, status code: 404)
- [ ] https://www.perplexity.ai/apple-icon-180x180.png (file: content/stuff/perplexity-ai.md, status code: 404)
- [ ] https://pbs.twimg.com/profile_images/1354831201693917185/DwU2Fy9K_400x400.jpg (file: content/stuff/planetscale.md, status code: 404)
- [ ] https://pomotimer.com/apple-touch-icon.png (file: content/stuff/pomotimer.md, status code: 404)
- [x] https://practice.dev (file: content/stuff/practice-dev.md, status code: 500)
- [x] https://practice.dev/favicon.png (file: content/stuff/practice-dev.md, status code: 404)
- [x] https://www.programmr.com/ (file: content/stuff/programmr.md, error: ECONNRESET)
- [x] https://www.programmr.com/sites/default/files/programr_theme2013_favicon_0.png (file: content/stuff/programmr.md, error: ECONNRESET)
- [ ] https://radicle.xyz/favicon.svg (file: content/stuff/radicle.md, status code: 404)
- [ ] https://pbs.twimg.com/profile_images/1337188620222906368/oNKK_fVe_400x400.jpg (file: content/stuff/render.md, status code: 404)
- [x] https://runjs.app/ (file: content/stuff/runjs.md, error: ENOTFOUND)
- [x] https://runjs.app/static/icon.png (file: content/stuff/runjs.md, error: ENOTFOUND)
- [ ] https://seatable.io/wp-content/uploads/2020/06/logo.svg (file: content/stuff/SeaTable.md, status code: 404)
- [ ] https://seeklogo.com/img/favicon.ico (file: content/stuff/seeklogo.md, status code: 404)
- [ ] https://pbs.twimg.com/profile_images/1621375028528050176/LlabgxHC_400x400.jpg (file: content/stuff/serp-ai.md, status code: 404)
- [x] https://www.sniptt.com/ots/ (file: content/stuff/sniptt.md, status code: 404)
- [ ] https://snyk.io/wp-content/themes/snyk_v2_etyhadar/dist/images/svg/logo.svg (file: content/stuff/snyk.md, status code: 404)
- [ ] https://stackoverflow.com/jobs (file: content/stuff/stack-overflow-job.md, status code: 404)
- [x] https://getstisla.com/ (file: content/stuff/stisla.md, error: ECONNRESET)
- [x] https://getstisla.com/landing/stisla.png (file: content/stuff/stisla.md, error: ECONNRESET)
- [ ] https://pbs.twimg.com/profile_images/1454912483248930822/_hO4WPRC_400x400.png (file: content/stuff/student-hubmicrosoft.md, status code: 404)
- [x] https://getsturdy.com/ (file: content/stuff/sturdy.md, error: EPROTO)
- [ ] https://getsturdy.com/assets/SwimmingDuck512.717387fb.png (file: content/stuff/sturdy.md, error: EPROTO)
- [ ] https://pbs.twimg.com/profile_images/1397471927132844033/jN-wuufb_400x400.jpg (file: content/stuff/supabase.md, status code: 404)
- [ ] https://swimm.io/img/favicon.ico (file: content/stuff/swimm.md, status code: 404)
- [ ] https://tara.ai/_nuxt/img/floating-logo.f615f40.svg (file: content/stuff/tara-ai.md, status code: 404)
- [ ] https://pbs.twimg.com/profile_images/1349315440707833857/FVio6cQy_400x400.png (file: content/stuff/tatum.md, status code: 404)
- [x] https://www.thunderclient.io/ (file: content/stuff/thunder-client.md, error: ENOTFOUND)
- [x] https://www.thunderclient.io/images/thunder-1024.png (file: content/stuff/thunder-client.md, error: ENOTFOUND)
- [x] https://tilde.so/ (file: content/stuff/tilde.md, error: ENOTFOUND)
- [x] https://tilde.so/brand/favicon_256.png (file: content/stuff/tilde.md, error: ENOTFOUND)
- [ ] https://toggl.com/plan/images/webclip.png (file: content/stuff/toggl-plan.md, status code: 404)
- [ ] https://unicode-table.com/i/favicons/apple-icon-180x180.png (file: content/stuff/unicode_character_table.md, status code: 404)
- [ ] https://upstash.com/static/icons/apple-touch-icon.png (file: content/stuff/upstash.md, status code: 404)
- [ ] https://www.vagrantup.com/img/logo-hashicorp.svg (file: content/stuff/Vagrant.md, status code: 404)
- [ ] https://pbs.twimg.com/profile_images/1252531684353998848/6R0-p1Vf_400x400.jpg (file: content/stuff/vercel.md, status code: 404)
- [ ] https://virt-manager.org/wp-content/themes/virtman/favicon.ico (file: content/stuff/virtual-machine-manager-home.md, status code: 404)
- [x] https://weworkremotely.com/ (file: content/stuff/we-work-remotely.md, status code: 500)
- [ ] https://www.weblab.ai/favicon.png (file: content/stuff/weblab-javascript.md, status code: 404)
- [ ] https://play.google.com/store/apps/details?id=com.yaaratech.remote.jobs (file: content/stuff/work-from-home-jobs.md, status code: 404)
- [ ] https://www.linkpicture.com/q/Wttr.in.png (file: content/stuff/wttr.md, status code: 404)
- [x] https://link.to.service (file: content/example.md, error: ENOTFOUND)
- [x] https://any.logo.of/service (file: content/example.md, error: ENOTFOUND)
- [ ] https://aiml.careers/images/apple-icon.png (file: content/stuff/aiml-jobs.md, status code: 404)
- [ ] https://www.algolia.com/algoliaweb-static-favicons/apple-touch-icon.png (file: content/stuff/algolia.md, status code: 404)
- [ ] https://allma.io/static/f9f486935d131403d00fed7f8e3b22f2/e8f31/allma-logo.png (file: content/stuff/Allma.md, status code: 404)
- [x] https://a-compress.co (file: content/stuff/autocompress.md, error: EAI_AGAIN)
- [ ] https://a-compress.co/icons/icon-512x512.png?v=8f4a62f6f6f19202cba30f0d75bf66bc (file: content/stuff/autocompress.md, error: EAI_AGAIN)
- [ ] https://www.balena.io/static/favicon-a2725b7c5213ad90b1d527e8f7448318.ico (file: content/stuff/balena.md, status code: 404)
- [ ] https://basecamp.com/basecamp-icon-196x196.png (file: content/stuff/basecamp.md, status code: 404)
- [ ] https://wac-cdn.atlassian.com/assets/img/favicons/bitbucket/apple-touch-icon.png (file: content/stuff/bitbucket-pipeline.md, status code: 404)
- [ ] https://wac-cdn.atlassian.com/assets/img/favicons/bitbucket/apple-touch-icon.png (file: content/stuff/bitbucket.md, status code: 404)
- [ ] https://cloudbrowser.io/bonsai-logo.svg (file: content/stuff/bonsai-web-browser.md, error: EPROTO)
- [ ] https://3fxtqy18kygf3on3bu39kh93-wpengine.netdna-ssl.com/wp-content/themes/browserstack/img/favicons/apple-touch-icon.png (file: content/stuff/browserstack.md, error: ENOTFOUND)
- [ ] https://pbs.twimg.com/profile_images/1422256068554641413/iR0aoxSO_400x400.jpg (file: content/stuff/buildspace.md, status code: 404)
- [ ] https://www.bytebase.com/favicon.ico (file: content/stuff/bytebase.md, status code: 404)
- [ ] https://www.checklyhq.com/images/racoon_favicon.1f21491a.png (file: content/stuff/checkly.md, status code: 404)
- [ ] https://cloudcannon.com/assets/cc-emblem-with-text-blue.svg (file: content/stuff/cloudcannon.md, status code: 404)
- [ ] https://pbs.twimg.com/profile_images/1414743035074670610/TEGu0j4L_400x400.png (file: content/stuff/cloudinary.md, status code: 404)
- [ ] https://pbs.twimg.com/profile_images/1171375829382774784/70ZgE-ke_400x400.png (file: content/stuff/codesandbox.md, status code: 404)
- [x] https://cronit.app (file: content/stuff/cronit.md, error: EAI_AGAIN)
- [x] https://cronit.app/static/apple-touch-icon.png (file: content/stuff/cronit.md, error: EAI_AGAIN)
- [ ] https://www.cryptocareers.dev/ (file: content/stuff/cryptocareers-dev.md, status code: 404)
- [ ] https://www.cypress.io/icons/icon-512x512.png?v=90213ca87017074111a88470199bc242315d18c5 (file: content/stuff/cypress-io.md, status code: 404)
- [ ] https://pbs.twimg.com/profile_images/1477550326739832833/8wSCGwjk_400x400.jpg (file: content/stuff/deepsource.md, status code: 404)
- [ ] https://pbs.twimg.com/profile_images/1542728772352462848/kNZnYAM2_400x400.png (file: content/stuff/digital-ocean-app.md, status code: 404)
- [ ] https://www.docker.com/sites/default/files/d8/2019-07/vertical-logo-monochromatic.png (file: content/stuff/docker.md, status code: 404)
- [ ] https://www.drovio.com/assets/images/logo-header-2.svg (file: content/stuff/drovio.md, status code: 404)
- [ ] https://pbs.twimg.com/profile_images/1499837137339891715/30EyQj2H_400x400.png (file: content/stuff/edgedb.md, status code: 404)
- [ ] https://engagespot.co/assets/images/Group-2-3-100x100.png (file: content/stuff/engagespot.md, status code: 404)
- [ ] https://pbs.twimg.com/profile_images/1151104422287687680/DAAkvhpA_400x400.png (file: content/stuff/fathym.md, status code: 404)
- [ ] https://finishmytask.online (file: content/stuff/finish-my-task.md, error: ECONNREFUSED)
- [ ] https://finishmytask.online/apple-touch-icon.png (file: content/stuff/finish-my-task.md, error: ECONNREFUSED)
- [ ] https://firecamp.io/icons/icon-512x512.png?v=111fa166e59046b135ba4ec749ba5725 (file: content/stuff/firecamp.md, status code: 404)
- [ ] https://flaviocopes.com/assets/apple-touch-icon.png (file: content/stuff/flaviocopes-ebook.md, status code: 404)
- [ ] https://fly.io/ui/images/favicon/apple-touch-icon.png (file: content/stuff/fly.md, status code: 404)
- [x] https://ffa.aakhilv.me (file: content/stuff/FunFactAPI.md, error: ECONNRESET)
- [ ] https://pbs.twimg.com/profile_images/714866842419011584/LRrR48qp_400x400.jpg (file: content/stuff/gitkraken.md, status code: 404)
- [ ] https://cdn03.gitter.im/_s/899bed3ee/images/favicon-normal.ico (file: content/stuff/gitter.md, error: ENOTFOUND)
- [ ] https://marketingplatform.google.com/about/analytics/ (file: content/stuff/google-analytics.md, error: ECONNREFUSED)
- [ ] https://goorm.io/icons/icon-512x512.png?v=031f6d228c5347f59da8275131f62141 (file: content/stuff/goorm.md, status code: 404)
- [ ] https://harperdb.io/app/themes/harperdb/dist/images/icons/harperdb-icon-192x192.png (file: content/stuff/harperdb.md, status code: 404)
- [ ] https://heroicons.com/_next/static/media/apple-touch-icon.a91ed695b6b4eded51810cb94c91a093.png (file: content/stuff/heroicons.md, status code: 404)
- [ ] https://pbs.twimg.com/profile_images/1438778186469306371/IbJoDwEO_400x400.jpg (file: content/stuff/hoppscotch.md, status code: 404)
- [ ] https://httpdump.io/assets/logo/icon-86a7b4fb3a6a21ca7c0f5d4d9d5f68368c50ec3edbbc4f2ff95bbe1c00786d42.png (file: content/stuff/httpdump.md, status code: 404)
- [ ] https://hypercore-protocol.org/images/hypercore-protocol.svg (file: content/stuff/hypercore_protocol.md, status code: 404)
- [ ] https://www.infinityfree.net/assets/favicon-43c4d910328657634c2bd0b6840a6360c7341f0c36513ef67ef28546036b24dd.ico (file: content/stuff/infinityfree.md, status code: 404)
- [ ] https://pbs.twimg.com/profile_images/1433473181575270400/ezcXnx8v_400x400.jpg (file: content/stuff/jam.md, status code: 404)
- [ ] https://www.jsonrpc.org/assets/ico/favicon.ico (file: content/stuff/jsonrpc.md)
- [ ] https://pbs.twimg.com/profile_images/1325755376168546305/MWtGzxMf_400x400.jpg (file: content/stuff/june-analytics-app.md, status code: 404)
- [ ] https://gblobscdn.gitbook.com/spaces%2F-MQ3mYNSOjNkHuQB7Nyt%2Favatar-1609619403028.png?alt=media (file: content/stuff/kryptor.md, status code: 400)
- [ ] https://pbs.twimg.com/profile_images/1381901268050976774/-YafbmFO_400x400.jpg (file: content/stuff/layer0.md, status code: 404)
- [ ] https://pbs.twimg.com/profile_images/978105765658427392/Vh2UKpPG_400x400.jpg (file: content/stuff/leantime.md, status code: 404)
- [ ] https://uselemon.io/assets/favicon/favicon.ico (file: content/stuff/lemon.md, status code: 404)
- [x] https://masedi.net/lemper (file: content/stuff/lemper-stack.md, error: ECONNRESET)

**Comment by hilmanski** [comment]
thank you so much for the report!
