### ISSUE TITLE
Correct Spelling and Grammar

### ISSUE THREAD

**Issue by seblex9** [hilmanski/freeStuffDev#1365]
I'd like to make the main page easier to read. Specifically, I want to fix any spelling and grammar issues in the short description on the left hand side of the site as well as the "what is this" section at the bottom of the right side. 

These changes might be small, but they'll make a big difference in how the page looks and reads.

**Comment by aniketkumar7** [comment]
I want to contribute assigned it to me.

**Comment by harshita1611** [comment]
I would like to work on this issue please assign it to me

**Comment by anushka9555** [comment]
I would like to work on this issue. Please assign

**Comment by AnshuWorld** [comment]
i want to contribute here please assign me

**Comment by kritikasharma4** [comment]
I am interested to contribute Can you please assign this issue to me

**Comment by hilmanski** [comment]
since there's no follow up from original author, I'll close this for now. Feel free to reopen with more clear message on what needs to be updated

**Comment by seblex9** [comment]
> since there's no follow up from original author, I'll close this for now. Feel free to reopen with more clear message on what needs to be updated

Hi, Hilmanski. I may have misunderstood but I was under the impression I was to raise the issue, wait for you to approve, and then I handle it myself. Sorry if I misunderstood.
