### ISSUE TITLE
[Feature request] Scroll to Top button

### ISSUE THREAD

**Issue by ayushshukla011** [hilmanski/freeStuffDev#1368]
A scroll to top button is a must have feature that every modern website must have .In order to ease user experience.
/assign 
@hilmanski

**Comment by vishalverma9572** [comment]
I would like to work on this. may I ?

**Comment by hilmanski** [comment]
Feel free to open a PR @kaligone

**Comment by kaligone** [comment]
> Feel free to open a PR @kaligone

Not getting , how to run this on localhost?

**Comment by vishalverma9572** [comment]
Just run your default.html on live server

**Comment by kaligone** [comment]
> Just run your default.html on live server

Not getting such file , can you clarify more

**Comment by kaligone** [comment]
> Feel free to open a PR @kaligone

@hilmanski Can you please tell how to run on localhost to add feature?

**Comment by hilmanski** [comment]
Hi, This project is using Hugo static site generator
You can learn from Hugo documentation https://gohugo.io/

**Comment by hilmanski** [comment]
@ayushshukla011  or @vishalverma9572  would you like to work on this issue?

**Comment by vishalverma9572** [comment]
Yes! Sir I am working on this, bcz i am working on Hugo website for the first time that is why I am facing some issue, But please give some time I will generate PR soon..

**Comment by vishalverma9572** [comment]
@hilmanski  I have generated a PR. Please check it and let me know..
