### ISSUE TITLE
cyclic.sh is shutting down and no longer allows signups

### ISSUE THREAD

**Issue by Jan69** [hilmanski/freeStuffDev#1664]
https://www.cyclic.sh/posts/cyclic-is-shutting-down/

> Effective immediately we are turning off signups by new users.
> In two weeks, May 10th, we will begin turning off free tier usage.
> We will begin turning off all usage May 31.

even the TLS certificate has expired, though the site's still up

**Comment by hilmanski** [comment]
Thanks, addressed here: https://github.com/hilmanski/freeStuffDev/commit/f75f7c6f7132e0a78c5d48b392edb54d5d310d2a
