### ISSUE TITLE
Add Tag for OS

### ISSUE THREAD

**Issue by linibensonjr** [hilmanski/freeStuffDev#188]
Could there be a section on each freeStuff to indicate what platform each is available on. It would save time, so someone knows if the program is available on only Mac or Windows or even both or more.

For example, I had to click the visit link for Warp Terminal to realize it was only for Mac OS. While Termius is available on Mac, Windows, Linus and also mobile

**Comment by hilmanski** [comment]
Hi interseting idea. Currently we don't have those, as it requires to tagging all items one by one.
What could be useful is our search that very flexible, if you search "windows" or any keyword it will automatically filter out if the item has that text

**Comment by hilmanski** [comment]
And don't forget each of the item is editable by public, so you can add more information there

**Comment by linibensonjr** [comment]
> Hi interseting idea. Currently we don't have those, as it requires to tagging all items one by one. What could be useful is our search that very flexible, if you search "windows" or any keyword it will automatically filter out if the item has that text

Okay great, I think this works fine then, thanks.
