### ISSUE TITLE
Save my favorites tools

### ISSUE THREAD

**Issue by djego** [hilmanski/freeStuffDev#214]
Maybe useful to have option for save favorite tools only localstorage initially, so as not to generate an additional infrastructure cost

**Comment by hilmanski** [comment]
Hi Djego, Indeed I was thinking about it once. 
But I'll wait until maybe around 3-5 people requested for it.

**Comment by shrn01** [comment]
This would be a great addition to the site

**Comment by taljacob2** [comment]
Yes please!

**Comment by hilmanski** [comment]
Thanks @djego  @shrn01  @taljacob2 
Will work on it

**Comment by hilmanski** [comment]
Hi guys. It's live!
you can save on each card 
And see your list at https://freestuff.dev/favorites/

https://github.com/hilmanski/freeStuffDev/commit/8ef1d456b48a48933fc14b9c01300a31d6956417
