### ISSUE TITLE
Transforming the Normal Links in the cards to Buttons will surely improve the user interface and experience.

### ISSUE THREAD

**Issue by ampsteric** [hilmanski/freeStuffDev#247]
The encircled items in the below image can be made much more interactive.

![image](https://user-images.githubusercontent.com/56419358/193209833-6439335e-c86e-4077-9904-9d41e1479dae.png)

Let me know what you think, if you agree I can surely start working on it.

**Comment by hilmanski** [comment]
Hi @ampsteric appreciate your concern.
But RN we're intentionally make it look simple and minimalist
