### ISSUE TITLE
Can we have the items alphabetically ordered? Does this make sense?

### ISSUE THREAD

**Issue by shrn01** [hilmanski/freeStuffDev#249]

**Comment by hilmanski** [comment]
Thansk @shrn01  for you idea.
I don't think alphabetic order bring any value.
But I have a plan to add "two sections"
1. sort from newest (like we have right now)
2. sort by random

The aim for the second is so 'old tools' can get a second chance to be viewed by visitors

**Comment by Tushar-TW** [comment]
@hilmanski can i work on this?

**Comment by hilmanski** [comment]
@Tushar-TW yes you can.
Here's the rough spec.

1. We can add text here: Order: 'random' or 'new' . The two is clickable text.
<img width="928" alt="Screen Shot 2022-10-09 at 05 19 33" src="https://user-images.githubusercontent.com/4522467/194728167-3ed36f92-7b22-4333-8f94-5ee5c9c0b5cb.png">

2 (Option A) Random as default. Hugo is a static site generator, so the 'random' here means -> random on every build. I already have a running script that run the generator at least once a day. While 'new' is what we have now.

3. (Option B) We can also play by the javascript logic. has nothing to do with Hugo. 

Feel free to pick what you want

**Comment by shrn01** [comment]
I feel it's better to go with Option A, as the user might have seen some resource he wants to use and he mistakenly did a refresh, the order is most probably retained so he can go ahead and use that

**Comment by hilmanski** [comment]
Thanks for your input @shrn01 .
@Tushar-TW will let you work on it. feel free to confirm / cancel.

**Comment by Tushar-TW** [comment]
I’m currently working on it

**Comment by arpanbiki** [comment]
please assign me this sir.

**Comment by hilmanski** [comment]
@Tushar-TW can you verify are you still working on this?

**Comment by Tushar-TW** [comment]
@hilmanski you can assign this to anyone else

**Comment by hilmanski** [comment]
@arpanbiki assigned this to you as you requested

**Comment by shrn01** [comment]
Hey @hilmanski how do I run the site locally?

**Comment by hilmanski** [comment]
This project built on Hugo.
So you need to learn Hugo first https://gohugo.io/

**Comment by hilmanski** [comment]
@arpanbiki in 2 days if no update, I assume you're not working on it, so I'll remove your acc from assignees (LMK otherwise). thanks

**Comment by hilmanski** [comment]
Now we have the ability to sort list on two different formats:
by newest (default) and random

https://github.com/hilmanski/freeStuffDev/commit/5e53447f9f2d7840e04b2be55377819b578e19ba
