### ISSUE TITLE
Scroll bar looking weird in some places

### ISSUE THREAD

**Issue by shrn01** [hilmanski/freeStuffDev#261]
I was just browsing the site and I saw that at few places we are getting a scrollbar and it's making the UI somewhat cluttered there. Attaching a screenshot for reference. 

My System details
|   |   |
|---|---|
CHROME VERSION |  106.0.5249.103
OS VERSION |  Windows NT: 10.0.22000

![image](https://user-images.githubusercontent.com/50091666/195368622-a0be99a1-0948-4fb9-a7c3-b588a8c10427.png)

**Comment by hilmanski** [comment]
Hi @shrn01 
Yap it's intentional to make a certain card not goes too long. (and yes, thats ugly :) )
If you think its better without, feel free to make the PR

**Comment by danangtomo** [comment]
mas @hilmanski ,can you assign this issue to me?

**Comment by danangtomo** [comment]
> @hilmanski ,can you assign this issue to me?

I tried to make changes locally, change the default style of the scrollbar, reduce the width of the size and also provide the distance between the scrollbar and the list of _free offer_ .

preview :
wdyt?

![image](https://user-images.githubusercontent.com/26623057/195714793-74ff9e32-8984-43d4-9b11-e97e698561b0.png)

**Comment by shrn01** [comment]
@danangtomo  Looks like you're not on windows. Can you raise a PR so that we can see if works?

**Comment by danangtomo** [comment]
> @danangtomo Looks like you're not on windows. Can you raise a PR so that we can see if works?

I use windows too, well it looks the same as you too @shrn01 
yes I am waiting if there is a change request from the owner of this repo, then I will make a PR

**Comment by hilmanski** [comment]
already assigned to you @danangtomo 
thanks for working on this

**Comment by hilmanski** [comment]
Fixed at https://github.com/hilmanski/freeStuffDev/pull/267
