### ISSUE TITLE
api in freeStuffDev?

### ISSUE THREAD

**Issue by codehangen** [hilmanski/freeStuffDev#302]
Hi all.

I'm thinking of creating a [presearch](https://presearch.io/) module to search software links, open source projects. I wanted to know if you've thought about creating an api to query links in freeStuffDev.

#### image
![image](https://user-images.githubusercontent.com/111701513/202629073-e490b32f-54ba-4b59-9d63-ae6ee9c63f62.png)

**image-description:** As we can see in this image I can query freeStuffDev links within presearch.

**Comment by hilmanski** [comment]
Hi @codehangen 
I'm not really familiar with presearch. 

But to answer your question, currently we have this https://freestuff.dev/stuff/index.json that could represent the "API"
