### ISSUE TITLE
awesome-projects and freeStuffDev

### ISSUE THREAD

**Issue by codehangen** [hilmanski/freeStuffDev#303]
Hi all.

#### 1. concept and initial problem
I want to know if you've all thought about adding links to open source communities on freeStuffDev, the idea would be for anyone to have information where the communities are, in addition to knowing about the main software, open source projects or libs, parsers too. 

#### 2. Why?
1. Personally, I love this project and would like to know if this idea is good or not.
2. I could add the community links for Gnome, Mint, Ubuntu etc. This allows me to be more assertive, instead of having a bunch of links in browser(like google chrome, edge, firefox etc) to access.
3. My idea is that this repository is awesome-links, where we add links to open source communities (ie contact), or add links to open source projects and posts that are good. This makes it easier to search for certain things.
4. Currently, being able to remember many links to access is complicated. And that could make my life easier or that of many programmers who need an open, distributed repository of links.

#### 3.1 content/stuff/awesome_rank_project.md
```yaml
+++
date = 2022-11-17T15:32:46.311Z
title = "Awesome Rank Project"
link = "https://awesomerank.github.io/"
thumbnail = "https://awesomerank.github.io/favicon.png"
snippet="😎 Awesome lists about all kinds of interesting topics with rank"
tags = ["organization"]
+++
```

#### 3.2 content/stuff/gnome_community.md
```yaml
+++
date = 2022-11-17T15:32:46.311Z
title = "GNOME"
link = "https://wiki.gnome.org/Infrastructure/GitHub"
thumbnail = "https://static.gnome.org/img/gnome-logo.svg"
snippet="The GNOME Infrastructure is currently managing a mirror of gitlab.gnome.org (specifically the GNOME group) on [GitHub](https://wiki.gnome.org/GitHub)."
tags = ["organization"]
+++
```

#### 4.1 content/stuff/awesome_rank_project

![image](https://user-images.githubusercontent.com/111701513/202708353-e7d10ed1-7ba9-4459-80ac-0f836bdef8b9.png)

#### 4.2 content/stuff/gnome_community

![image](https://user-images.githubusercontent.com/111701513/202707703-11e5a632-a43a-44cd-b1f8-5e69b50ce5cc.png)

**image-description** As we can see in the image, we have links to the organization of each open project. As well as, we have links to each open project as well. On the other hand, links to the technical documentation of each open project could complement this idea. As well as, we could complement the idea, have links to library files, parsers, reading recommendations, etc.

*What do you all think of this idea?*

**Comment by hilmanski** [comment]
Hi correct me if I'm wrong.

You can submit anything as longs as it's related to developer.
you just need to tag "community" to organize it
