### ISSUE TITLE
new properties and values in freeStuff dev

### ISSUE THREAD

**Issue by codehangen** [hilmanski/freeStuffDev#325]
Hi all.

#### 1. Idea
A random idea I had today would be to have 4 links: ``link_homepage``, ``link_documentation``, ``link_community``, ``link_repository``. My idea would be to have an array of links.

#### 1.1 example: link_sitename_or_project.md
```
+++
date = 2022-11-19T14:30:43.478Z
title = "Sample sitename or project"
link = ["https://sample-sitename.com/docs/", "https://sample-sitename.com/community/", "https://sample-sitename.com/homepage/", "https://sample-sitename.com/source-code/"]
thumbnail = "https://sample-sitename.com/AnzKNLZrk0Lw_400x400.jpg"
snippet="Sample sitename or project, description."
license="MIT or BSD or Copyright"
tags = ["tag1","tag2", "source-code"]
+++
```

**code-description:** As we can see in this code snippet, we have the license property that refers to the license of the software or project, which can be ``MIT``, ``GPL`` etc. And we have an array of links where we can insert multiple links: ``link_homepage``, ``link_documentation``, ``link_community``, ``link_repository``.

#### 2. concept
![image](https://user-images.githubusercontent.com/111701513/203061463-c077dee4-2233-4af8-b361-8e0ba3cc3e60.png)

**image-description:** As we can see in this image, we have the license property and an array of links where we can insert multiple links: ``link_homepage``, ``link_documentation``, ``link_community``, ``link_repository``.

*What do you all think of the idea?*

**Comment by hilmanski** [comment]
Hi nice idea. But for now, I think it'll add more burden to contributor.
Which against our principle, to make the submission very simple
