### ISSUE TITLE
contributors information at README.md

### ISSUE THREAD

**Issue by ghost** [hilmanski/freeStuffDev#332]
Hi everyone.

I would like to know your opinion on the idea of ​​adding the freeStuffdev contributor information. *Is this idea good or bad?*

*What do you all think of the idea?(I would be happy to help or have new feedback on this idea.)*

**Comment by hilmanski** [comment]
Hi. Can you elaborate WDYM by contributor information?

**Comment by sharmaudit124** [comment]
Hey can you please assign this issue to me?

**Comment by hilmanski** [comment]
@codehangen Hi. I mean what do you mean by "contributor information" ? Since Github already have list of contributors of each repo
