### ISSUE TITLE
add md5 to filename.md

### ISSUE THREAD

**Issue by codehangen** [hilmanski/freeStuffDev#333]
Hi all.

One of the things I noticed that is manual is that we have to manually add the file name. A random idea that came to my mind would be to have random names for md files. Which makes the link automation or link curation part of freeStuffdev easier.

This could be done with the md5 algorithm which generates unique hashes.

#### 85e4fbf2a38f643a66d4558762d2b2bc.md
![image](https://user-images.githubusercontent.com/111701513/204078497-639dcc47-4d63-4d16-b5e2-57fb274abbe7.png)

#### 1.2 Idea
![image](https://user-images.githubusercontent.com/111701513/204078563-ea97569d-a0dd-4ddc-b6e5-5e2cd304850c.png)

*What do you all think of the idea?(I would be happy to help or have new feedback on this idea.)*

**Comment by hilmanski** [comment]
Hi. We prefer to have a clear name for the file for now.
Thanks for the great suggestion
