### ISSUE TITLE
add CodeOfConduct.md in freeStuffDev?

### ISSUE THREAD

**Issue by codehangen** [hilmanski/freeStuffDev#358]
Hi all.

I wonder if you've all thought about adding the file: CodeOfConduct in the README.md. *Have you thought about adding the file: CodeOfConduct.md in freeStuffDev?*

#### What is CodeOfConduct?
A code of conduct is a set of values, rules, standards, and principles outlining what employers expect from staff within an organization.

*What do you all think of the idea?*

**Comment by hilmanski** [comment]
Hi we have the CoC on the site https://freestuff.dev/codeofconduct/
Feel free to add it on readme as well
