### ISSUE TITLE
add donate url in freeStuffDev?

### ISSUE THREAD

**Issue by ghost** [hilmanski/freeStuffDev#372]
Hi everyone.

I was wondering if this repository couldn't have a donation link. Someone might want to help the project through financial resources. 

#### Idea
![image](https://user-images.githubusercontent.com/111701513/204645341-ecfea607-ea83-4dc8-86e9-977e94d7163b.png)

#### Question
Have you all thought about providing a donation link to help the project?

#### Why?
- This allow bug-bounty(Paying for developing a feature, support, backup, automation, improvement, cloud, storage, update, fixed, ui/ux, security, issue, ci/cd, networking, hosting, domain etc).
- Someone might want to help the project through financial resources.

#### "Options"
PayPal, OpenCollective, LiberaPay, Ko-fi etc.

#### Feedback
*What do you all think of the idea?*

**Comment by hilmanski** [comment]
Thanks for the suggestion, will let this open for now and see what other people think
