### ISSUE TITLE
freeStuffDev: decentralized and distributed?

### ISSUE THREAD

**Issue by ghost** [hilmanski/freeStuffDev#388]
Hi everyone.

Instead of adding 'localstorage', could we add 'remote-storage', IPFS and/or [solid-pod](https://solidproject.org/) to add bookmarks in freeStuffDev?

#### img 1.1
![image](https://user-images.githubusercontent.com/111701513/204820549-a805815a-0a06-4baa-b6a1-732b51747556.png)

#### img 1.2
![image](https://user-images.githubusercontent.com/111701513/204819986-2f00c3e6-1a71-4755-b62b-870467e5f286.png)

**image-description:** As we can see, we can choose the storage location, being dropbox, google drive, remote storage and/or localstorage for bookmarks in freeStuffDev.

#### Why ipfs?
- IPFS makes it simple to set up resilient networks for mirroring data, and thanks to content addressing, files stored using IPFS are automatically versioned.

#### Why solid-pod?
1. You can store any kind of data in a Solid Pod. What makes Solid special is the ability to store data in a way that promotes interoperability. 
2. Specifically, Solid supports storing Linked Data. Structuring data as Linked Data means that different applications can work with the same data.

#### Why remote-storage?
1. For users:
   - own your data: Everything in one place – your place. Use a storage account with a provider you trust, or set up your own storage server. Move house whenever you want. It’s your data.
   - stay in sync: remoteStorage-enabled apps automatically sync your data across all of your devices, from desktop to tablet to smartphone, and maybe even your TV or VR headset.
   - compatibility & choice: Use the same data across different apps. Create a to-do list in one app, and track the time on your tasks in another one. Say goodbye to app-specific data silos.
   - go offline: Most remoteStorage-enabled apps come with first-class offline support. Use your apps offline on the go, and automatically sync when you’re back online.
3. For developers:
   - backend as a service: Develop your web app without worrying about hosting or even developing the backend for it: your users will connect their own backend at runtime.
   - infinite scalability: No matter if 5 hundred or 5 million users are using your app, your backend scales automatically and never costs you a single cent.
   - wheels included: remoteStorage.js is a JavaScript library that does all the heavy-lifting of connecting to any remoteStorage backend, caching, synchronizing and storing user data.
4. For community:
    - decentralized, distributed application
    - protocol is open-source
    - 100% client-side apps that use remoteStorage, Google Drive, Dropbox, etc…, the developer provides only the app, while the user controls the device and data.
    - remoteStorage is a creative combination of existing protocols and standards. It aims to re-use existing technologies as much as possible, adding just a small layer of standardization on top to facilitate its usage for per-user storage with simple permissions and offline-capable data sync. like: WebFinger, OAuth 2.0, HTTP REST.

#### Or why 3 network protocols?
- these protocols are well known and used for large-scale distribution of decentralized applications, which work online/offline.
- these protocols are well known and used for [unhosted app](https://unhosted.org/)

#### Question/feedback
*What do you all think of the idea?*

**Comment by hilmanski** [comment]
Thanks for the suggestion.
Are you referring to this remotestorage -> https://remotestorage.io/ ?

Me myself not familiar with it. Let's see what other people think if there's any need for it
