### ISSUE TITLE
add freeStuffDev as organization?

### ISSUE THREAD

**Issue by ghost** [hilmanski/freeStuffDev#389]
Hi everyone.

I wonder if you've all thought about creating a freeStuffDev organization.

#### concept
- github.com/freeStuffDev/website
- github.com/freeStuffdev/tests
...

*or*
- github.com/freeStuffDev/logins "All urls for logins social-media"
- github.com/freeStuffDev/courses "All urls for courses-ti" 
- github.com/freeStuffDev/rss "All urls for rss"
- github.com/freeStuffDev/support "All urls for support"
- github.com/freeStuffDev/protocols "All urls for protocols: ipfs, remote-storage, hyperprotocol etc"
- github.com/freeStuffDev/forum "All urls for forum"
- github.com/freeStuffDev/networking "All urls for networking"
- github.com/freeStuffDev/jobs "All urls for jobs"
- github.com/freeStuffDev/news "All urls for news"
- github.com/freeStuffDev/android-apps "All urls for android open source"
- github.com/freeStuffDev/ios-apps "All urls for ios open source"
- github.com/freeStuffDev/smartphone-linux-apps "All urls for smartphone-linux open source"
- github.com/freeStuffDev/browser-extensions "All urls for browser extensions"
- github.com/freeStuffDev/showcase-languageprogramming "All urls for language-programming, showcase"
- github.com/freeStuffDev/scientific-articles "All urls for scientific-articles"
- github.com/freeStuffDev/download-os "All urls for os download"
- github.com/freeStuffDev/db-tools "All urls for tools database open-source"
- github.com/freeStuffDev/hosting "All urls for hosting open-source"
- github.com/freeStuffDev/apps "All urls for apps open-source"
- github.com/freeStuffDev/plugins "All urls for plugins for development"
- github.com/freeStuffDev/communities   "All urls for communities-development"
- github.com/freeStuffDev/libs  "All urls for libs for development"
- github.com/freeStuffDev/widgets "All urls for widgets for development"
- github.com/freeStuffDev/os  "All urls for operating system: linux, windows, unix, dos etc"
- github.com/freeStuffDev/rfcs "All urls for rfcs in IETF, W3C, Python(Peps), Php(RFC's)..."
- github.com/freeStuffDev/docs "All urls for documentation: tiddlywiki, manjaro etc"
- github.com/freeStuffDev/well-known  "A curated list of well-known URIs, resources, guides and tools"

*What do you all think of the idea?*

**Comment by hilmanski** [comment]
Thanks for the suggestion
Is this pointing to have a separate repo and site for every category?

For now, I prefer for it on one repo and one site, to not overcomplicate things
