### ISSUE TITLE
chrome extension for freeStuffDev?

### ISSUE THREAD

**Issue by ghost** [hilmanski/freeStuffDev#391]
Hi everyone.

#### concept
My idea would be to create an extension in the browser to send and receive links of freeStuffdev.

#### Idea
![image](https://user-images.githubusercontent.com/111701513/204890457-e680c950-4d01-457d-9b08-6e72b808bfd9.png)

**image-description:** As we can see in the image, there is an extension in the browser. Mozilla bought the pocket.io company and made it open source. This image refers to getpocket.io, a program that saves links to read later.

*What do you all think of the idea?*

**Comment by hilmanski** [comment]
Appreciate the suggestion.

Like other features, I normally wait if other people need it, before spending your time on it

If it's something you would use for yourself, I would say go for it. But remember to save a link on FSD , you need to send a PR. There's no "API".
