### ISSUE TITLE
pull request

### ISSUE THREAD

**Issue by ghost** [hilmanski/freeStuffDev#398]
Hi everyone.

I would like to know the reason for these two pull requests not being accepted. Because... both are support, discussion and development forums.

- [hilmanski/freeStuffDev/pull/309](https://github.com/hilmanski/freeStuffDev/pull/309)
- [hilmanski/freeStuffDev/pull/311](https://github.com/hilmanski/freeStuffDev/pull/311)

*I would like feedback on this if possible.*

**Comment by hilmanski** [comment]
Sure,
Tiddlywiki is a "general product" which is not just for developer. We can still accept the Tiddlywiki itself, but to add the "forum discussion" I think already over stretch this site.

And on top of that, a discussion forum for another language. I think it's more way off. I'll close it, but feel free to ask again if it's not clear
