### ISSUE TITLE
image with default(if image without return)

### ISSUE THREAD

**Issue by codehangen** [hilmanski/freeStuffDev#418]
Hi all.

Instead of leaving an image blank, can we leave a default image like this?

#### 1.1 before.html
```html
<img src loading="lazy" alt="Logo Free MySQL Hosting -" width="80" height="auto">
```

#### 1.2 after.html
```html
<img src="https://i.ibb.co/ZHwQF1b/Screen-Shot-2022-09-23-at-15-50-49-removebg-preview.png" loading="lazy" alt="Logo Free MySQL Hosting -" width="80" height="auto">
```

#### 2.1 before
![image](https://user-images.githubusercontent.com/111701513/205104352-6a444163-024e-4206-a5ad-bac467849433.png)

#### 2.2 after
![image](https://user-images.githubusercontent.com/111701513/205104097-2a96bd0d-2bbb-432e-b6c5-9b057deda00a.png)

*What do you all think of the idea?*

**Comment by hilmanski** [comment]
Nice idea. I think we need to do something for unprovided image. 
But rather than giving a template image, I would prefer just hide the image. 

I'll work on this
