### ISSUE TITLE
bot on differents platforms to update freeStuffDev links?

### ISSUE THREAD

**Issue by ghost** [hilmanski/freeStuffDev#442]
Hi everyone.

#### Concept
This is my last idea and contribution. *My general idea is to create a bot on discourse, delta-chat, telegram, discord to update freeStuffDev links.*

#### Question/feedback
*What do you all think of the idea?*

**Comment by hilmanski** [comment]
RE: "This is my last idea and contribution" - it's unfortunate, thanks for all your ideas and contributions

RE:  Creating a bot on diff platforms.
Like other feature, if it's something you want to use yourself, feel free to do so.
But if it's something you expect other people would use, my suggestion would be wait if there's any demand for it.
We can let this issue open, and see what other people think

Thanks, have a good day!
