### ISSUE TITLE
Mobile mode not responsive

### ISSUE THREAD

**Issue by mrofisr** [hilmanski/freeStuffDev#69]
![WhatsApp Image 2021-08-13 at 09 21 01](https://user-images.githubusercontent.com/31870041/129296136-f664d95e-2bb7-4619-911e-e4d1dee85f67.jpeg)

**Comment by hilmanski** [comment]
can you specify, which part do you mean not responsive?

**Comment by hilmanski** [comment]
It's a feature, not a bug :)
thanks
