### ISSUE TITLE
Trinket link broken

### ISSUE THREAD

**Issue by rondDev** [hilmanski/freeStuffDev#823]
The link to Trinket is broken due to the ref.

This link does not work: https://trinket.io/?ref=freeStuffDev
It returns a 403 Forbidden

If we remove the ref, it woks fine, like this: https://trinket.io/

**Comment by hilmanski** [comment]
thanks @rondDev will see what can we do about it. 
As we intentionally and automatically put ref on every link

**Comment by rondDev** [comment]
> and automatically put ref on every link

I am aware, just thought I'd let you know that it's an issue

**Comment by perpetualsquid** [comment]
@hilmanski is this fixed or is anything further needed? I'm asking because the PR has been merged but the issue is still open. Happy to contribute if anything is needed.
